CREATE TABLE mra (
    `versions_date` DATETIME,
    `versions_versionNumber` NUMERIC(2, 1),
    `versions_threads_name` VARCHAR(32) CHARACTER SET utf8,
    `versions_threads_subThreads_name` VARCHAR(62) CHARACTER SET utf8,
    `versions_threads_subThreads_helpText` VARCHAR(9) CHARACTER SET utf8,
    `versions_threads_subThreads_questions_questionText` VARCHAR(284) CHARACTER SET utf8,
    `versions_threads_subThreads_questions_level` INT
);
INSERT INTO mra VALUES ('2016-10-05 00:00:00',1.0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,'TM Placeholder Thread',NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,'Technology Maturity','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Technology Readiness at TRL 1 or greater?',1);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Technology Readiness at TRL 2 or greater?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Technology Readiness at TRL 3 or greater?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Technology Readiness at TRL 4 or greater?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Technology Readiness at TRL 5 or greater?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Technology Readiness at TRL 6 or greater?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Technology Readiness at TRL 7 or 8?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Technology Readiness at TRL 8 or 9?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Technology Readiness at TRL 9?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Technology Readiness at TRL 9?',10);
INSERT INTO mra VALUES (NULL,NULL,'A - Technology & Industrial Base',NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,'A.1 - Technology Transition to Production','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have potential manufacturing sources been identified for technology needs (Understand state of the art)?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have industrial base capabilities and gaps/risks been identified for key technologies, components, and/or key processes?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the industrial base capabilities assessment been initiated to identify potential manufacturing sources to produce the required capability?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have sole/single/foreign source vendors and vendors of technologies with potential obsolescence issues been identified? ',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has planning begun to minimize the risks associated with sole/single/foreign source vendors?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has an industrial base capabilities assessment for MS B been completed?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the industrial capability in place to support the manufacturing of development articles?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the plans to minimize sole/single/foreign sources and obsolescence issues complete?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the need for sole/single/foreign sources been justified?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have potential alternative sources been identified?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the industrial capability to support production been analyzed?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the stability of all sole/single/foreign sources and obsolescence issues being assessed/monitored?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the necessary alternates to sole/single/foreign sources being developed?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the industrial base capability assessment for Milestone C been completed?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the industrial capability in place to support Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all necessary sources available including multi-sourcing where cost-effective or necessary to mitigate risk?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the industrial capability assessment for FRP complete?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Industrial capability in place to support the start of FRP?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the Industrial Capability support FRP',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the industrial capability been assessed to support modifications, upgrades, surge, and other potential manufacturing requirements?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'A.2 - Manufacturing Technology Development','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have new manufacturing concepts and potential solutions been identified?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing technology concepts been identified through experiments/models?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have pertinent Manufacturing Science (MS) and Advanced Manufacturing Technology requirements been identified?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the required manufacturing technology development efforts been initiated as applicable?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the necessary manufacturing technology development efforts continuing?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the required manufacturing technology development solutions been demonstrated in a production relevant environment?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the necessary manufacturing technology development efforts still continuing?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the required manufacturing science and manufacturing technology development solutions been demonstrated in a production representative environment?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the primary manufacturing technology efforts concluding and some improvement efforts continuing?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the required manufacturing technology development solutions been validated on a pilot line?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the required manufacturing technology process improvement efforts been initiated for Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are manufacturing technology continuous process improvements ongoing?',10);
INSERT INTO mra VALUES (NULL,NULL,'B - Design',NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,'B.1 - Producibility Program','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have relevant materials/processes been evaluated for manufacturability using experiments/models?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are initial producibility and manufacturability assessments of preferred systems concepts completed?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the results of the producibility and manufacturability assessment being considered in the selection of preferred design concepts?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the results of the producibility and manufacturability assessment being reflected in the Technology Development Strategy key components/technologies?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have producibility & manufacturability assessments of key technologies and components been initiated as appropriate?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do ongoing design trades consider manufacturing processes and industrial base capability constraints? ',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the manufacturing processes been assessed for capability to test and verify in production and their influence on Operations and Support (O&S)?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have producibility assessments and producibility trade studies (performance vs. producibility) of key technologies/components been completed?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the results of the producibility assessments and trade studies being used to shape the Acquisition Strategy, Systems Engineering Plan (SEP), Manufacturing and Producibility plans, and Planning for Engineering and Manufacturing Development (EMD) or technology insertion programs?  ',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the preliminary design choices assessed against manufacturing processes and industrial base capability constraints? ',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the producibility enhancement efforts (e.g., Design For Manufacturing and Design for Assembly) initiated?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the detailed producibility trade studies using detailed knowledge of key design characteristics and related manufacturing process capabilities completed?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the producibility enhancement efforts (e.g., Design For Manufacturing and Design for Assembly) ongoing for an optimized integrated system?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are manufacturing processes re-assessed as needed for capability to test and verify potential influence on Operations & Support? ',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the producibility improvements been implemented on the system?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the known producibility issues been resolved and pose no significant risk for Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have prior producibility improvements been analyzed for effectiveness during Low Rate Initial Production (LRIP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the producibility issues/risks discovered in Low Rate Initial Production (LRIP) been mitigated and pose no significant risk for Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have design producibility improvements been demonstrated in Full Rate Production (FRP)?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are process producibility improvements ongoing?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all modifications, upgrades, Diminishing Mfg Sources & Material Shortages (DMSMS), and other changes assessed for producibility?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'B.2 - Design Maturity','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing research opportunities been identified?',1);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have applications been defined?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have broad performance goals been identified that may drive manufacturing options?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have top level performance requirements been defined?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have trade-offs in design options been assessed based on experiments?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are product lifecycle requirements and technical requirements being evaluated?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do the Systems Engineering Plan (SEP) and the Test and Evaluation Strategy recognize the need for the establishment/validation of manufacturing capability and management of manufacturing risk for the product lifecycle?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have initial potential Key Performance Parameters (KPPs) been identified for the preferred systems concept?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are system characteristics and measures to support required capabilities identified?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are form, fit, and function constraints and manufacturing capabilities identified for the preferred systems concepts?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are lower level performance requirements sufficient to proceed to the preliminary design?  ',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all enabling/critical technologies and components identified? ',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do enabling/critical technologies and components consider the product lifecycle? ',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the evaluation of design Key Characteristics (KC) been initiated? ',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have product data required for prototype component manufacturing been released?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a system allocated baseline been established?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the product requirements and features well enough defined to support Preliminary Design Review?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has product data essential for  subsystem/system prototyping been released?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all enabling/critical technologies/components been demonstrated?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have preliminary design Key Characteristics (KC) been defined and are mitigation plans in development?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the product design and features well enough defined to support critical design review even though design change traffic may be significant?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has all the product data essential for component manufacturing been released?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have potential Key Characteristic risk issues been identified?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have preliminary design Key Characteristic (KC) issues been defined and are mitigation plans in development?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the detailed design of product features and interfaces complete?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has all the product data essential for system manufacturing been released?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the design change traffic have minimal impact on Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the Key Characteristics attainable based upon pilot line demonstrations?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the major product design features and configuration stable?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the system design been validated through operational testing of Low Rate Initial Production (LRIP) items?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the Physical Configuration Audit (PCA) or equivalent complete as necessary?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the design change traffic limited to minor configuration changes?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all Key Characteristics controlled in Low Rate Initial Production (LRIP) to appropriate quality levels?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the product design stable (i.e. design changes are few and generally limited to those required for continuous improvement or in reaction to obsolescence)? ',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all Key Characteristics controlled in Full Rate Production (FRP) to appropriate quality levels?',10);
INSERT INTO mra VALUES (NULL,NULL,'C - Cost & Funding',NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,'C.1 - Production Cost Knowledge (Cost modeling)','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the cost model approach been defined?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have initial cost targets and risks been identified? ',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a high level process chart model been developed? ',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have technology cost models been developed for new process steps and materials based on experiments?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have key manufacturing, material and specialized requirement cost drivers been identified?    ',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are detailed process chart cost models driven by process variables?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has cost driver uncertainty been quantified?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do prototype components or simulations produced in a production relevant environment drive the formulation of the final production cost model?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is there a realistic cost model that includes  materials, labor, equipment, tooling/Special Test Equipment (STE), setup, yield/scrap/rework, Work In Progress (WIP), and capability/capacity constraints?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have cost models been updated with design requirements, material specifications, tolerances, integrated master schedule, results of system/subsystem simulations and  production relevant prototype demonstrations?  ',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are cost models updated with the results of systems/sub-systems produced in a production representative environment, production plant layout and design, and obsolescence solutions?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have cost models been updated with results of the pilot line build?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the Full Rate Production (FRP) cost model been updated with the result of the Low Rate Initial Production (LRIP) build?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the cost model been validated against actual Full Rate Production (FRP) cost?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'C.2 - Cost Analysis','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing cost implications been identified?',1);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have cost elements been identified?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a sensitivity analysis been conducted to define cost drivers and production development strategy (i.e. lab to pilot to factory)?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have producibility cost risks been assessed?  ',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,' Do initial cost models support Analysis of Alternatives (AoA) and Alternative Systems Review (ASR)?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are costs analyzed using prototype component actuals to ensure target costs are achievable? ',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are decisions regarding design choices, make/buy, capacity, process capability, sources, quality, key characteristics, yield/rate, and variability influenced by cost models?   ',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are costs analyzed using prototype system/sub-system actuals to ensure target costs are achievable? ',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have cost targets been allocated to subsystems?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have cost reduction and avoidance strategies been developed?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the manufacturing cost drivers for "Should-Cost" models been provided?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the manufacturing costs been rolled up to the system/sub-system level and been tracked against targets?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,' Are detailed trade studies and engineering change requests supported by cost estimates?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are cost reduction and avoidance strategies underway?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the manufacturing cost drivers for "Should-Cost" models been updated?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are costs analyzed using pilot line actuals to ensure target costs are achievable? ',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does manufacturing cost analysis support proposed changes to requirements or configuration?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the cost reduction initiatives ongoing?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have Low Rate Initial Production (LRIP) cost goals been met and has the learning curve been analyzed with actual data?  ',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the cost reduction initiatives still ongoing?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the manufacturing cost drivers for "Should-Cost" models been updated?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has touch labor efficiency been analyzed to meet production rates?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have elements of inefficiency for touch labor been identified with plans in place for reduction?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have Full Rate Production (FRP) cost goals been met?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the cost reduction initiatives continuing?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'C.3 - Manufacturing Investment Budget','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have potential investments been identified?',1);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do the program/projects have reasonable budget estimates for reaching MRL 3 through experiment?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do the program/projects have reasonable budget estimates for reaching MRL 4 by Milestone A?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing technology initiatives been identified to reduce costs?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the program have a reasonable budget estimate to reach MRL 6 by Milestone B?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the cost estimate include capital investment for production-relevant equipment?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all outstanding MRL 4 risk areas understood with approved mitigation plans in place?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the program have an updated budget estimate for reaching MRL 6 by Milestone B?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all outstanding MRL 5 risk areas understood with approved mitigation plans in place?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the program have a reasonable budget estimate for reaching MRL 8 by Milestone C?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the cost estimate include capital investment for production-representative equipment by CDR and pilot line equipment by Milestone C?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all outstanding MRL 6 risk areas understood with approved mitigation plans in place?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the program have an updated budget estimate for reaching MRL 8 by Milestone C?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all outstanding MRL 7 risk areas understood with approved mitigation plans in place?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the program have a reasonable budget estimate for reaching MRL 9 by the Full Rate Production (FRP) decision point?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the cost estimate include investment for Low Rate Initial Production (LRIP) and Full Rate Production (FRP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all outstanding MRL 8 risk areas understood with approved mitigation plans in place?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the program have a reasonable budget estimate for Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all outstanding MRL 9 risk areas understood with approved mitigation plans in place?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the production budgets sufficient for production at the required rates and schedule to support the funded program?',10);
INSERT INTO mra VALUES (NULL,NULL,'D - Materials',NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,'D.1 - Maturity','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material properties been identified for research?',1);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material properties and characteristics been predicted?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material properties been validated and assessed for basic manufacturability using experiments?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have projected materials been produced in a laboratory environment?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all materials been manufactured or produced in a prototype environment (may be in a similar application/program)?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are maturation efforts in place to address new material production risks for technology demonstration?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the material maturity been verified with technology demonstration articles?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are preliminary material specifications in place?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material properties been adequately characterized?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the material maturity sufficient for a pilot line build?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the necessary material specifications been approved?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the materials been proven and validated during Engineering and Manufacturing Development (EMD) as adequate to support Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are material specifications stable?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all necessary materials been proven and controlled to specification in Low Rate Initial Production (LRIP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the materials proven and validated as adequate to support FRP?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all necessary materials been proven and controlled to specification in Full Rate Production (FRP)?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'D.2 - Availability','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has material availability been assessed?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material scale-up issues been identified?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have projected lead times been identified for all difficult to obtain, difficult to process, or hazardous materials?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material quantities and lead times been estimated?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material availability issues been addressed for the prototype build?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have significant material risks been identified for all materials?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has planning begun to address scale-up issues?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material availability issues been addressed to meet Engineering and Manufacturing Development (EMD) build?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have Long-lead items been identified?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have potential obsolescence issues been identified?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have components been assessed for future DMSMS risk?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material availability issues been addressed to meet Engineering and Manufacturing Development (EMD) builds?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have long lead procurements been identified/planned for Low Rate Initial Production (LRIP)?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is an obsolescence plan in place?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are mitigation strategies in place for DMSMS components?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have long lead procurements been initiated for Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are material availability risk issues minimized for Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have availability Issues been addressed to meet FRP needs?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have long lead procurements been initiated for Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are availability risk issues minimized for Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all significant Full Rate Production (FRP) material availability risk issues resolved?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'D.3 - Supply Chain Management','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has an initial assessment of potential supply chain capability been completed?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a survey for potential supply chain sources been completed?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have potential supply chain sources been identified and evaluated as able to support prototype build?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have life cycle supply chain requirements and the critical suppliers list been updated?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are supply chain plans (e.g., teaming agreements, etc.) in place leading to an Engineering and Manufacturing Development (EMD) contract award?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is there an effective supply chain management process defined, documented and in place?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a plan been developed for establishing predictive indicators?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has an adequate assessment of the critical first tier supply chain been completed (i.e., capability, capacity, etc.)?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the supply chain adequate to support Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has an adequate assessment of the critical second and lower tier supply chain been completed?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is there a robust and disciplined requirements flow-down process verified and in place?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has supplier compliance with program requirements and changes been validated?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the plan for predictive indicators been updated for use in production?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the supply chain stable and adequate to support Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are long term agreements in place where practical?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the Prime''s supplier management metrics (including thresholds and goals) in place and being used to manage risk?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are predictive indicators in place to manage suppliers?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the supply chain been proven to support Full Rate Production (FRP) requirements?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'D.4 - Special Handling','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has an initial evaluation of potential regulatory requirements and special handling concerns been completed?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a list of hazardous materials been identified?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have potential special handling procedures been applied in the lab?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have special handling concerns been assessed?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a list of hazardous materials been updated?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have special handling requirements been identified?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the special handling procedures been applied in the lab?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have special handling procedures been applied in a production relevant environment?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all special handling requirement gaps been identified?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have new special handling processes been demonstrated in lab environment?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have special handling procedures been applied in a production relevant environment?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the plans to address the special handling requirement gaps been completed?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have special handling procedures been applied in a production representative environment?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have special handling procedures been developed and annotated on work instructions for the pilot line?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have special handling procedures been applied in a pilot line environment?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have special handling procedures been demonstrated in Engineering and Manufacturing Development (EMD) or technology insertion programs?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the special handling risk issues been minimized for Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do all work instructions contain special handling provisions as required?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have special handling procedures been applied in a Low Rate Initial Production (LRIP) environment?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the special handling procedures been demonstrated in Low Rate Initial Production (LRIP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the special handling risk issues been minimized for Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the special handling procedures been effectively implemented in Full Rate Production (FRP)?  ',10);
INSERT INTO mra VALUES (NULL,NULL,'E - Process Capability & Control',NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,'E.1 - Modeling & Simulation','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have initial models been developed, if applicable?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have proposed manufacturing concepts or producibility needs been identified based on high-level process flow chart models?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have production modeling and simulation approaches for process or product been identified?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the initial simulation models (product or process) been developed at the component level and used to determine constraints?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the initial simulation models been developed at the technology sub-system or system level and used to determine system constraints?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the simulation models been used to determine system constraints and identify improvement opportunities?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the simulation models been verified by the pilot line? ',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the results of the simulation models been used to improve processes and determine that Low Rate Initial Production (LRIP) requirements can be met?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the simulation models been verified by Low Rate Initial Production (LRIP) build and used to assist in management of Low Rate Initial Production (LRIP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the results of the simulation models been used to determine if Full Rate Production (FRP) requirements can be met?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the simulation models been verified by Full Rate Production (FRP) build?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the production simulation models been used as a tool to assist in management of Full Rate Production (FRP)?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'E.2 - Manufacturing Process Maturity','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material and/or process approaches been identified?',2);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have high level manufacturing processes been documented?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have critical manufacturing processes been identified through experimentation?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a survey been completed to determine the current state of critical processes?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has process maturity been assessed on similar processes in production?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have process capability requirements been identified for pilot line, Low Rate Initial Production (LRIP) and Full Rate Production (FRP)?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the key manufacturing processes been demonstrated in a production relevant environment?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has collecting or estimating process capability data from prototype build begun, and have process capability requirements been refined? ',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the manufacturing processes been successfully demonstrated in a production representative environment?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has collecting or estimating process capability data continued? ',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have process capability requirements been refined?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the manufacturing processes for Low Rate Initial Production (LRIP) been verified on a pilot line?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does capability data from the pilot line meet the target?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have process capability requirements for LRIP been refined based on Pilot Line data?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the manufacturing processes stable, adequately controlled, capable, and have the manufacturing processes achieved program  Low Rate Initial Production (LRIP) objectives?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have variability experiments been conducted to show Full Rate Production (FRP) impact and potential for continuous improvement? ',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the manufacturing processes stable, adequately controlled, capable, and have the manufacturing processes achieved program  Full Rate Production (FRP) objectives?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'E.3 - Process Yields and Rates','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have initial estimates of yields and rates based on experiments or state of the art been completed?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a yield and rates assessment on proposed/similar processes been completed?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a yield and rates assessment on proposed/similar processes been applied within the Analysis of Alternatives (AoA)?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have target yield and rates been established for the pilot line, Low Rate Initial Production (LRIP), and Full Rate Production (FRP)?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have yield and rate issues been identified and does the detailed production schedule support the required production rate?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have yield and rate improvement plans been developed/initiated?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are yields and rates from the production relevant environment being evaluated against targets?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are results from the yields and rates from the production relevant environment being fed into an improvement plan?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are yields and rates from the production representative environment being evaluated against pilot line targets?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are results from the yields and rates from the production representative environment being fed into  improvement plans?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have pilot line yield and rate targets been achieved?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have yields and rates required to begin Low Rate Initial Production (LRIP) been refined using pilot line articles?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are yield and rate improvement plans ongoing and being updated?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the Low Rate Initial Production (LRIP) yield and rate targets been achieved?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the results of LRIP yields and rates been used to refine FRP yield requirements?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are yield improvements on-going?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the Full Rate Production (FRP) yield and rate targets been achieved?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are yield improvements on-going?',10);
INSERT INTO mra VALUES (NULL,NULL,'F - Quality Management',NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,'F.1 - Quality Management including Supplier Quality','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a quality strategy been identified as part of the Acquisition Strategy (AS)?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the updated quality strategy included in the System Engineering Plan (SEP)?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the quality strategy been updated to reflect Key Characteristic identification activities?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is there an initial Quality Plan (QP) and a Quality Management System (QMS) in place?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have quality risks and adequate metrics been identified and improvement plans initiated?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the quality targets been established?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do Quality Management System (QMS) elements (e.g., control of nonconforming material, corrective action, etc.) meet requirements of appropriate industry standards?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is a program-specific quality plan being developed?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the program-specific quality plan and Quality Manager been established?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have quality targets been assessed against the pilot line to see if they drive continuous quality improvement?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have quality targets been verified on the Low Rate Initial Production (LRIP) line?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is continuous quality improvement on-going?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is management review of quality targets conducted on a regular basis with appropriate action being taken?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the quality targets been verified on the Full Rate Production (FRP) line?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is continuous quality improvement on-going?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are statistical controls being applied where appropriate?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'F.2 - Product Quality','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a product inspection and acceptance testing strategy been identified as part of the Acquisition Strategy?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a product inspection and acceptance testing strategy been included in the Systems Engineering Plan (SEP)?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have roles and responsibilities been identified for acceptance test procedures, in-process and final inspections? ',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have statistical process controls been identified for prototype units?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a Key Characteristic management approach been defined?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have initial requirements been identified for acceptance test procedures and in-process and final inspection requirements for EMD units?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have appropriate inspection and acceptance test procedures been identified for prototype units?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has quality data from the production representative environment been collected and analyzed and the results used to shape improvement plans?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are control plans completed for management of Key Characteristics?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are Test and Inspection Plans being developed for EMD units?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are Key Characteristics managed with measurement procedures and controls in place (e.g. SPC, FRACAS, audits, customer satisfaction, etc.)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does the Pilot line data meet capability requirements for all Key Characteristics?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are Test and Inspection Plans complete and validated for production units?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does data from LRIP demonstrate that production processes for all Key Characteristics and other manufacturing processes critical to quality are capable and under control for FRP?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the quality of Key Characteristics controlled at rate, and the data reflects only rare and unrepeated quality issues related to manufacturing processes?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do results of quality data achieve targeted statistical level on all Key Characteristics?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do results of quality data reflect continuous improvement?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'F.3 - Supplier Quality Management','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are potential supplier base quality capabilities and risks identified, to include subtier supplier quality management? ',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have supply base quality capabilities and risks been identified, to include subtier quality management?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have specific supply base quality improvement initiatives been identified addressing supplier Quality Management System shortfalls, including subtier supplier quality management?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do key supplier Quality Management Systems meet appropriate industry standards? ',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has supplier quality data from production representative units been collected and analyzed?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a strategy been outlined for audits of critical supplier processes?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are supplier program-specific Quality Management Systems adequate ?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have supplier products completed qualification testing?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have supplier products completed first article inspection?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is acceptance testing of supplier products adequate to begin LRIP?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is a plan for subcontractor process audits in place and being implemented by prime contractor?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does supplier management of quality of Key Characteristics and other critical manufacturing processes demonstrate capability and control for FRP?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does acceptance testing of supplier products reflects control of quality adequate to begin FRP?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are subcontractor Quality Audits performed as necessary to ensure subcontractor specification compliance?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does supplier quality data reflect adequate management of Key Characteristics and control of critical manufacturing processes, including quality management down to subtier suppliers?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Does process quality achieve high statistical level (e.g. 6-sigma) on all critical dimensions? ',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are subcontractor Quality Audits performed as necessary to ensure subcontractor specification compliance?',10);
INSERT INTO mra VALUES (NULL,NULL,'G - Mfg Personnel',NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,'G.1 - Manufacturing Personnel','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have new manufacturing skills been identified?',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing skill sets been identified?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have production workforce requirements (technical and operational) been evaluated as part of AoA?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the availability of process development workforce for the Technology Maturation and Risk Reduction Phase been determined?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the necessary workforce skill sets been identified to meet prototype production needs?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have plans for the identified skill sets been developed to meet prototype production needs?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have special skills certification and training requirements been established?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the manufacturing workforce skills available for production in a relevant environment?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have resources (quantities and skill sets) been identified to achieve requirements for pilot line and production? ',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have initial plans for the identified resources (quantities and skill sets) been developed to achieve requirements for pilot line and production? ',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the manufacturing workforce resource requirements been identified for the pilot line?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,' Have plans been developed to achieve pilot line requirements?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,' Have plans been updated to achieve Low Rate Initial Production (LRIP) workforce requirements? ',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the pilot line workforce been trained in the representative environment?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing workforce resource requirements been identified for Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,' Have plans been developed to achieve Low Rate Initial Production (LRIP) requirements?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,' Have plans been updated to achieve  Full Rate Production (FRP) workforce requirements? ',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have Low Rate Initial Production (LRIP) personnel been trained on the pilot line where possible?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have Low Rate Initial Production (LRIP) personnel requirements been met?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a plan been implemented to achieve Full Rate Production (FRP) workforce requirements?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have Full Rate Production (FRP) personnel requirements been met including all necessary certifications?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are production workforce skill sets being maintained due to attrition of the workforce?',10);
INSERT INTO mra VALUES (NULL,NULL,'H - Facilities',NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,'H.1 - Tooling/ Special Test and Inspection Equipment (STE/SIE)','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are tooling/Special Test Equipment (STE)/Special Inspection Equipment (SIE) requirements being considered as part of AoA?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have tooling and STE/SIE requirements been identified?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have supporting rationale and a schedule been provided for the tooling and STE/SIE requirements? ',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have prototype tooling and STE/SIE concepts been demonstrated in production relevant environment? ',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have production tooling and STE/SIE requirements been developed?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are production tooling and STE/SIE design and development efforts underway?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a manufacturing equipment maintenance strategy been developed?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all tooling, test, and inspection equipment been proven on the pilot line?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all tooling, test and inspection equipment requirements been identified for Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has manufacturing equipment maintenance been demonstrated on pilot line?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all tooling, test, and inspection equipment been proven in the Low Rate Initial Production (LRIP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has all tooling, test, and inspection equipment been proven in LRIP and additional requirements identified for Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a manufacturing equipment maintenance schedule been demonstrated?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is proven tooling, test, and inspection equipment in place to support maximum Full Rate Production (FRP)?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a planned equipment maintenance schedule been achieved?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'H.2 - Facilities','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have specialized facility requirements/needs been identified? ',3);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the availability of manufacturing facilities for prototype development and production been evaluated as part of the Analysis of Alternatives (AoA)?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing facilities been identified to produce prototypes?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have plans for the identified manufacturing facilities been developed to produce prototypes?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing facilities been identified to produce the pilot line build?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have plans for the identified manufacturing facilities been developed to produce the pilot line build?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing facilities been identified to produce the Low Rate Initial Production (LRIP) build?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have plans for the identified manufacturing facilities been developed to produce the Low Rate Initial Production (LRIP) build?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have pilot line facilities been demonstrated?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are manufacturing facilities adequate to begin Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are plans in place to support the transition to Full Rate Production (FRP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is workplace safety adequate?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing facilities been demonstrated in Low Rate Initial Production (LRIP)? ',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are capacity plans adequate to support Full Rate Production (FRP)? ',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the production facilities in place to meet Full Rate Production (FRP) requirements?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the capacity of the production facilities been demonstrated to meet Full Rate Production (FRP) requirements?',10);
INSERT INTO mra VALUES (NULL,NULL,'I - Mfg Management',NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,'I.1 - Mfg Planning & Scheduling','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has a manufacturing strategy been developed and integrated with an acquisition strategy?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have prototype schedule risk mitigation efforts been incorporated into the Acquisition Strategy (AS)?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the manufacturing strategy been refined based upon the preferred concept?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have prototype schedule risk mitigation efforts been initiated?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the initial manufacturing approach been developed?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are all system design related manufacturing events included in the Integrated Master Plan/Schedule (IMP/S)?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the manufacturing risk mitigation approach for the pilot line or technology insertion programs been defined?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the initial manufacturing plan been developed?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has manufacturing planning required to achieve MRL 8 been included in the Integrated Master Plan/Schedule (IMP/S)?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have manufacturing risks been integrated into risk mitigation plans?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have initial work instructions been developed? ',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is an effective production control system in place to support the pilot line? ',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the manufacturing plan been updated for Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all key manufacturing risks been identified and assessed with approved mitigation plans in place?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have work instructions been finalized? ',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is an effective production control system in place to support Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the manufacturing plan been updated for Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all manufacturing risks been tracked and mitigated?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is an effective production control system in place to support Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have all manufacturing risks been mitigated?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,'I.2 - Materials Planning','Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the technology development article component list been developed with associated lead time estimates?',4);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Is the technology development part list maturing?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have make/buy evaluations begun?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Do the make/buy evaluations include production considerations reflecting the pilot line, Low Rate Initial Production (LRIP), and Full Rate Production (FRP) needs?',5);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are most material decisions complete (make/buy)?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material risks been identified? ',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material risk mitigation plans been developed?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the Bill of Materials (BOM) been initiated?',6);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the make/Buy decisions and Bill of Materials (BOM) complete for pilot line build?  ',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are material planning systems in place for the pilot line build?',7);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the Make/Buy decisions and Bill of Materials (BOM) complete to support Low Rate Initial Production (LRIP)?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have material planning systems been proven on the pilot line and are in place for Low Rate Initial Production (LRIP) build?',8);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Are the Make/Buy decisions and Bill of Materials (BOM) complete enough to support Full Rate Production (FRP)?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Has the material planning system been proven in LRIP, and is it sufficient for Full Rate Production (FRP?',9);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,'Have the material planning systems been validated on the Full Rate Production (FRP) build?',10);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,'Help Text',NULL,NULL);
INSERT INTO mra VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL);
